# Raw ECG 환자 단위 SCD 학습·평가

`DL/data/final_split_v2_augmented.csv`의 PID·split·SCD를 그대로 사용합니다. 파일 형식은 현재 관측된 `(sample, 3)` float16을 기준으로 하며, 로더의 2 lead 처리는 합성 데이터로 확인했습니다. CNN → LSTM/Transformer → masked attention MIL → MLP 구조입니다.

전체 split 파일이 준비되면 같은 코드로 실행합니다. 원본 NPY에서 확인되지 않은 sample rate·배열 축는 upstream provenance와 대조해야 하며, `source_metadata_confirmed: true`는 확인 후에만 설정합니다. 30초 segment별 quality CSV(`pid,window_index,usable`)가 없으면 학습을 중단합니다. 구체적인 명령과 제한은 `DL/TRAINING.md`를 참고하세요.

유도 이름을 가정하지 않도록 공유 1유도 CNN을 모든 실제 유도에 적용한 뒤 평균 통합합니다. 배치의 유도 mask와 시간 mask는 별개이며, 양쪽 padding은 CNN/BatchNorm에서 제외합니다. 모델 선택 YAML은 `cnn_model`, `sequence_model`만 포함하고, threshold·MIL·MLP·학습 파라미터는 `training.yaml`에서 설정합니다.

환자 단위 MIL은 `training.yaml:mil.pooling`에서 `attention`(기본), `mean`, `max`를 선택합니다. Mean/max는 `mil: {pooling: mean}` 또는 `mil: {pooling: max}`처럼 설정하고 attention 전용 hidden_dim/activation/dropout을 제거합니다. 세 방식 모두 제외·패딩 시간 구간을 무시하고, 학습 snapshot으로 복원됩니다.

In [1]:
import json
import sys
from pathlib import Path

import pandas as pd
import torch
from torch.utils.data import DataLoader

repo = Path.cwd().resolve()
while not (repo / "Members/sang/model/DL/model_choice.yaml").is_file():
    if repo.parent == repo:
        raise RuntimeError("저장소 내부에서 노트북을 실행하세요")
    repo = repo.parent
if str(repo) not in sys.path:
    sys.path.insert(0, str(repo))

In [2]:
from Members.sang.model.config import (
    dl_config_paths,
    load_experiment_config,
    load_yaml,
    resolve_config_path,
)
from Members.sang.model.DL.composed import build_composed_model
from Members.sang.model.DL.dataloader.dataset import collate_patient_windows
from Members.sang.model.DL.dataloader.raw_waveform import RawPatientSequenceDataset, load_raw_cohort
from Members.sang.model.DL.dataloader.segmented_ecg import inspect_raw_cohort
from Members.sang.model.DL.raw_pipeline import train_raw_ecg
from Members.sang.model.inference import load_dl_run

choice_path = repo / "Members/sang/model/DL/model_choice.yaml"

/home/sang/sixletters-poc/Global/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 실행 설정·개인 계정

각 PC에서 한 번 `dev setup`으로 계정을 등록하면 이후 계정명을 노트북에 적지 않습니다. 환경 변수 `MLFLOW_TRACKING_*`와 `MLFLOW_EXPERIMENT_NAME`이 파일보다 우선합니다. 학습 전 표시되는 owner·username·experiment를 확인하세요. 기본은 고정 설정으로 학습 → validation → 최종 test → 개인 계정 MLflow 기록입니다. 모델 선택 중에는 test를 끕니다. 오프라인 실행은 `mlflow_logging=False`로 바꿉니다.

In [3]:
mlflow_logging = True
run_final_test = True
max_epochs = None
limit_train_patients = None
device_override = "auto"

if limit_train_patients is not None and run_final_test:
    raise ValueError("Smoke 학습에서는 run_final_test=False로 설정하세요.")

## 1. 설정과 현재 파일 감사

In [4]:
choice, basic, choice_path, basic_path = load_experiment_config(choice_path)
training = load_yaml(dl_config_paths(choice_path)["training"])
raw_config = basic["data"]["raw_ecg"]
records, inventory = inspect_raw_cohort(
    resolve_config_path(raw_config["split_path"], basic_path),
    resolve_config_path(raw_config["wave_directory"], basic_path),
)
display(pd.DataFrame(inventory["split_counts"]).T)
display(pd.DataFrame([record.__dict__ for record in records if record.reason]))
print("Split에 없는 파일:", inventory["wave_files_without_split_row"])
print("선택 모델:", choice["cnn_model"], choice["sequence_model"])

           patients positive negative files_present missing_or_invalid
train           349       96      253           349                 []
validation       71        8       63            71                 []
test             89       10       79            89                 []

Empty DataFrame
Columns: []
Index: []

Split에 없는 파일: ['P0001-1', 'P0001-2', 'P0002-1', 'P0002-2', 'P0003-1', 'P0003-2', 'P0004-1', 'P0004-2', 'P0006-1', 'P0006-2', 'P0007-1', 'P0007-2', 'P0009-1', 'P0009-2', 'P0010-1', 'P0010-2', 'P0013-1', 'P0013-2', 'P0014-1', 'P0014-2', 'P0015-1', 'P0015-2', 'P0017-1', 'P0017-2', 'P0018-1', 'P0018-2', 'P0019-1', 'P0019-2', 'P0022-1', 'P0022-2', 'P0023-1', 'P0023-2', 'P0024-1', 'P0024-2', 'P0029-1', 'P0029-2', 'P0033-1', 'P0033-2', 'P0036-1', 'P0036-2', 'P0037-1', 'P0037-2', 'P0041-1', 'P0041-2', 'P0042-1', 'P0042-2', 'P0043-1', 'P0043-2', 'P0045-1', 'P0045-2', 'P0048-1', 'P0048-2', 'P0049-1', 'P0049-2', 'P0050-1', 'P0050-2', 'P0051-1', 'P0051-2', 'P0052-1', 'P0052-2', 'P0053-1', 'P0053-2', 'P0055-1', 'P0055-2', 'P0059-1', 'P0059-2', 'P0061-1', 'P0061-2', 'P0062-1', 'P0062-2', 'P0063-1', 'P0063-2', 'P0064-1', 'P0064-2', 'P0068-1', 'P0068-2', 'P0071-1', 'P0071-2', 'P0072-1', 'P0072-2', 'P0076-1', 'P0076-2', 'P0079-1', 'P0079-2', 'P0082-1', 'P0082-2', 'P0086-1', 'P0086-2', 'P0088-1', 'P0088-2', 'P0090-1', 'P0090-2', 'P0091-1', 'P0091-2', 'P0092-1', 'P0092-2', 'P0093-1', 'P0093-2', 'P0096-1', 'P0096-2', 'P0097-1', 'P0097-2', 'P0098-1', 'P0098-2', 'P0100-1', 'P0100-2', 'P0101-1', 'P0101-2', 'P0102-1', 'P0102-2', 'P0103-1', 'P0103-2', 'P0104-1', 'P0104-2', 'P0105-1', 'P0105-2', 'P0106-1', 'P0106-2', 'P0124-1', 'P0124-2', 'P0126-1', 'P0126-2', 'P0128-1', 'P0128-2', 'P0130-1', 'P0130-2', 'P0131-1', 'P0131-2', 'P0132-1', 'P0132-2', 'P0133-1', 'P0133-2', 'P0137-1', 'P0137-2', 'P0142-1', 'P0142-2', 'P0145-1', 'P0145-2', 'P0146-1', 'P0146-2', 'P0147-1', 'P0147-2', 'P0154-1', 'P0154-2', 'P0158-1', 'P0158-2', 'P0164-1', 'P0164-2', 'P0166-1', 'P0166-2', 'P0169-1', 'P0169-2', 'P0171-1', 'P0171-2', 'P0174-1', 'P0174-2', 'P0175-1', 'P0175-2', 'P0179-1', 'P0179-2', 'P0181-1', 'P0181-2', 'P0182-1', 'P0182-2', 'P0184-1', 'P0184-2', 'P0189-1', 'P0189-2', 'P0190-1', 'P0190-2', 'P0191-1', 'P0191-2', 'P0193-1', 'P0193-2', 'P0195-1', 'P0195-2', 'P0196-1', 'P0196-2', 'P0197-1', 'P0197-2', 'P0198-1', 'P0198-2', 'P0201-1', 'P0201-2', 'P0202-1', 'P0202-2', 'P0203-1', 'P0203-2', 'P0204-1', 'P0204-2', 'P0206-1', 'P0206-2', 'P0208-1', 'P0208-2', 'P0209-1', 'P0209-2', 'P0210-1', 'P0210-2', 'P0214-1', 'P0214-2', 'P0216-1', 'P0216-2', 'P0219-1', 'P0219-2', 'P0220-1', 'P0220-2', 'P0222-1', 'P0222-2', 'P0227-1', 'P0227-2', 'P0228-1', 'P0228-2', 'P0230-1', 'P0230-2', 'P0231-1', 'P0231-2', 'P0234-1', 'P0234-2', 'P0235-1', 'P0235-2', 'P0236-1', 'P0236-2', 'P0237-1', 'P0237-2', 'P0238-1', 'P0238-2', 'P0240-1', 'P0240-2', 'P0244-1', 'P0244-2', 'P0247-1', 'P0247-2', 'P0249-1', 'P0249-2', 'P0252-1', 'P0252-2', 'P0253-1', 'P0253-2', 'P0254-1', 'P0254-2', 'P0258-1', 'P0258-2', 'P0259-1', 'P0259-2', 'P0261-1', 'P0261-2', 'P0271-1', 'P0271-2', 'P0272-1', 'P0272-2', 'P0273-1', 'P0273-2', 'P0274-1', 'P0274-2', 'P0277-1', 'P0277-2', 'P0281-1', 'P0281-2', 'P0282-1', 'P0282-2', 'P0283-1', 'P0283-2', 'P0288-1', 'P0288-2', 'P0292-1', 'P0292-2', 'P0295-1', 'P0295-2', 'P0296-1', 'P0296-2', 'P0297-1', 'P0297-2', 'P0302-1', 'P0302-2', 'P0304-1', 'P0304-2', 'P0305-1', 'P0305-2', 'P0306-1', 'P0306-2', 'P0307-1', 'P0307-2', 'P0310-1', 'P0310-2', 'P0311-1', 'P0311-2', 'P0312-1', 'P0312-2', 'P0314-1', 'P0314-2', 'P0315-1', 'P0315-2', 'P0316-1', 'P0316-2', 'P0318-1', 'P0318-2', 'P0319-1', 'P0319-2', 'P0323-1', 'P0323-2', 'P0324-1', 'P0324-2', 'P0325-1', 'P0325-2', 'P0326-1', 'P0326-2', 'P0328-1', 'P0328-2', 'P0330-1', 'P0330-2', 'P0331-1', 'P0331-2', 'P0334-1', 'P0334-2', 'P0335-1', 'P0335-2', 'P0337-1', 'P0337-2', 'P0338-1', 'P0338-2', 'P0341-1', 'P0341-2', 'P0342-1', 'P0342-2', 'P0343-1', 'P0343-2', 'P0344-1', 'P0344-2', 'P0346-1', 'P0346-2', 'P0347-1', 'P0347-2', 'P0348-1', 'P0348-2', 'P0350-1', 'P0350-2', 'P0352-1', 'P0352-2', 'P0354-1', 'P0354-2', 'P0358-1', 'P0358-2', 'P0361-1', 'P0361-2', 'P0366-1', 'P0366-2', 'P0371-1', 'P0371-2', 'P0372-1', 'P0372-2', 'P0373-1', 'P0373-2', 'P0379-1', 'P0379-2', 'P0380-1', 'P0380-2', 'P0388-1', 'P0388-2', 'P0392-1', 'P0392-2', 'P0402-1', 'P0402-2', 'P0406-1', 'P0406-2', 'P0408-1', 'P0408-2', 'P0417-1', 'P0417-2', 'P0420-1', 'P0420-2', 'P0421-1', 'P0421-2', 'P0436-1', 'P0436-2', 'P0441-1', 'P0441-2', 'P0442-1', 'P0442-2', 'P0443-1', 'P0443-2', 'P0444-1', 'P0444-2', 'P0454-1', 'P0454-2', 'P0457-1', 'P0457-2', 'P0462-1', 'P0462-2', 'P0465-1', 'P0465-2', 'P0474-1', 'P0474-2', 'P0475-1', 'P0475-2', 'P0478-1', 'P0478-2', 'P0479-1', 'P0479-2', 'P0484-1', 'P0484-2', 'P0485-1', 'P0485-2', 'P0488-1', 'P0488-2', 'P0490-1', 'P0490-2', 'P0492-1', 'P0492-2', 'P0493-1', 'P0493-2', 'P0495-1', 'P0495-2', 'P0497-1', 'P0497-2', 'P0505-1', 'P0505-2', 'P0506-1', 'P0506-2', 'P0507-1', 'P0507-2', 'P0508-1', 'P0508-2', 'P0511-1', 'P0511-2', 'P0512-1', 'P0512-2', 'P0514-1', 'P0514-2', 'P0515-1', 'P0515-2', 'P0516-1', 'P0516-2', 'P0517-1', 'P0517-2', 'P0518-1', 'P0518-2', 'P0519-1', 'P0519-2', 'P0522-1', 'P0522-2', 'P0523-1', 'P0523-2', 'P0524-1', 'P0524-2', 'P0525-1', 'P0525-2', 'P0527-1', 'P0527-2', 'P0528-1', 'P0528-2', 'P0530-1', 'P0530-2', 'P0531-1', 'P0531-2', 'P0534-1', 'P0534-2', 'P0538-1', 'P0538-2', 'P0539-1', 'P0539-2', 'P0541-1', 'P0541-2', 'P0542-1', 'P0542-2', 'P0543-1', 'P0543-2', 'P0547-1', 'P0547-2', 'P0548-1', 'P0548-2', 'P0549-1', 'P0549-2', 'P0551-1', 'P0551-2', 'P0552-1', 'P0552-2', 'P0557-1', 'P0557-2', 'P0559-1', 'P0559-2', 'P0561-1', 'P0561-2', 'P0562-1', 'P0562-2', 'P0564-1', 'P0564-2', 'P0566-1', 'P0566-2', 'P0569-1', 'P0569-2', 'P0572-1', 'P0572-2', 'P0574-1', 'P0574-2', 'P0575-1', 'P0575-2', 'P0577-1', 'P0577-2', 'P0578-1', 'P0578-2', 'P0581-1', 'P0581-2', 'P0588-1', 'P0588-2', 'P0590-1', 'P0590-2', 'P0591-1', 'P0591-2', 'P0595-1', 'P0595-2', 'P0597-1', 'P0597-2', 'P0598-1', 'P0598-2', 'P0600-1', 'P0600-2', 'P0603-1', 'P0603-2', 'P0604-1', 'P0604-2', 'P0606-1', 'P0606-2', 'P0608-1', 'P0608-2', 'P0609-1', 'P0609-2', 'P0610-1', 'P0610-2', 'P0611-1', 'P0611-2', 'P0613-1', 'P0613-2', 'P0614-1', 'P0614-2', 'P0617-1', 'P0617-2', 'P0620-1', 'P0620-2', 'P0621-1', 'P0621-2', 'P0625-1', 'P0625-2', 'P0626-1', 'P0626-2', 'P0627-1', 'P0627-2', 'P0628-1', 'P0628-2', 'P0636-1', 'P0636-2', 'P0637-1', 'P0637-2', 'P0639-1', 'P0639-2', 'P0640-1', 'P0640-2', 'P0641-1', 'P0641-2', 'P0642-1', 'P0642-2', 'P0644-1', 'P0644-2', 'P0645-1', 'P0645-2', 'P0646-1', 'P0646-2', 'P0648-1', 'P0648-2', 'P0652-1', 'P0652-2', 'P0653-1', 'P0653-2', 'P0654-1', 'P0654-2', 'P0655-1', 'P0655-2', 'P0656-1', 'P0656-2', 'P0658-1', 'P0658-2', 'P0659-1', 'P0659-2', 'P0660-1', 'P0660-2', 'P0661-1', 'P0661-2', 'P0662-1', 'P0662-2', 'P0663-1', 'P0663-2', 'P0664-1', 'P0664-2', 'P0668-1', 'P0668-2', 'P0669-1', 'P0669-2', 'P0670-1', 'P0670-2', 'P0671-1', 'P0671-2', 'P0672-1', 'P0672-2', 'P0673-1', 'P0673-2', 'P0674-1', 'P0674-2', 'P0675-1', 'P0675-2', 'P0676-1', 'P0676-2', 'P0677-1', 'P0677-2', 'P0678-1', 'P0678-2', 'P0681-1', 'P0681-2', 'P0682-1', 'P0682-2', 'P0683-1', 'P0683-2', 'P0684-1', 'P0684-2', 'P0685-1', 'P0685-2', 'P0686-1', 'P0686-2', 'P0687-1', 'P0687-2', 'P0693-1', 'P0693-2', 'P0694-1', 'P0694-2', 'P0695-1', 'P0695-2', 'P0698-1', 'P0698-2', 'P0699-1', 'P0699-2', 'P0700-1', 'P0700-2', 'P0701-1', 'P0701-2', 'P0702-1', 'P0702-2', 'P0709-1', 'P0709-2', 'P0710-1', 'P0710-2', 'P0721-1', 'P0721-2', 'P0724-1', 'P0724-2', 'P0726-1', 'P0726-2', 'P0727-1', 'P0727-2', 'P0729-1', 'P0729-2', 'P0736-1', 'P0736-2', 'P0738-1', 'P0738-2', 'P0739-1', 'P0739-2', 'P0741-1', 'P0741-2', 'P0743-1', 'P0743-2', 'P0744-1', 'P0744-2', 'P0745-1', 'P0745-2', 'P0746-1', 'P0746-2', 'P0751-1', 'P0751-2', 'P0753-1', 'P0753-2', 'P0755-1', 'P0755-2', 'P0756-1', 'P0756-2', 'P0763-1', 'P0763-2', 'P0778-1', 'P0778-2', 'P0780-1', 'P0780-2', 'P0787-1', 'P0787-2', 'P0789-1', 'P0789-2', 'P0791-1', 'P0791-2', 'P0808-1', 'P0808-2', 'P0812-1', 'P0812-2', 'P0814-1', 'P0814-2', 'P0815-1', 'P0815-2', 'P0818-1', 'P0818-2', 'P0824-1', 'P0824-2', 'P0826-1', 'P0826-2', 'P0827-1', 'P0827-2', 'P0828-1', 'P0828-2', 'P0831-1', 'P0831-2', 'P0832-1', 'P0832-2', 'P0833-1', 'P0833-2', 'P0834-1', 'P0834-2', 'P0849-1', 'P0849-2', 'P0852-1', 'P0852-2', 'P0856-1', 'P0856-2', 'P0859-1', 'P0859-2', 'P0861-1', 'P0861-2', 'P0862-1', 'P0862-2', 'P0864-1', 'P0864-2', 'P0865-1', 'P0865-2', 'P0866-1', 'P0866-2', 'P0868-1', 'P0868-2', 'P0871-1', 'P0871-2', 'P0875-1', 'P0875-2', 'P0878-1', 'P0878-2', 'P0883-1', 'P0883-2', 'P0889-1', 'P0889-2', 'P0893-1', 'P0893-2', 'P0894-1', 'P0894-2', 'P0895-1', 'P0895-2', 'P0900-1', 'P0900-2', 'P0901-1', 'P0901-2', 'P0902-1', 'P0902-2', 'P0903-1', 'P0903-2', 'P0905-1', 'P0905-2', 'P0909-1', 'P0909-2', 'P0910-1', 'P0910-2', 'P0911-1', 'P0911-2', 'P0912-1', 'P0912-2', 'P0914-1', 'P0914-2', 'P0915-1', 'P0915-2', 'P0922-1', 'P0922-2', 'P0923-1', 'P0923-2', 'P0924-1', 'P0924-2', 'P0925-1', 'P0925-2', 'P0926-1', 'P0926-2', 'P0928-1', 'P0928-2', 'P0930-1', 'P0930-2', 'P0931-1', 'P0931-2', 'P0935-1', 'P0935-2', 'P0937-1', 'P0937-2', 'P0939-1', 'P0939-2', 'P0941-1', 'P0941-2', 'P0943-1', 'P0943-2', 'P0945-1', 'P0945-2', 'P0956-1', 'P0956-2', 'P0962-1', 'P0962-2', 'P0971-1', 'P0971-2', 'P0973-1', 'P0973-2', 'P0974-1', 'P0974-2', 'P0976-1', 'P0976-2', 'P0977-1', 'P0977-2', 'P1001-1', 'P1001-2', 'P1002-1', 'P1002-2', 'P1054-1', 'P1054-2']
선택 모델: ResNet BiLSTM

## 2. 품질 인덱스 검증·로더·모델 생성

현재 quality CSV/provenance 확인이 없으면 이 셀에서 명확한 오류로 중단합니다. 누락 파일 때문에 환자를 다른 split으로 옮기지 않습니다. 모델 입력은 최대 `training.yaml:max_segments_per_patient`개의 유효 segment이며, 균등 간격으로 선택한 원래 segment 위치를 보존합니다. 정규화 기본값은 `none`입니다.

In [5]:
cohorts, usable_indices, audit = load_raw_cohort(basic, basic_path, require_quality=True)
display(pd.DataFrame(audit["split_summary"]).T)
max_segments = int(training["max_segments_per_patient"])
train_dataset = RawPatientSequenceDataset(
    cohorts["train"], usable_indices, raw_config, max_segments, raw_config["normalization"]
)
train_loader = DataLoader(
    train_dataset,
    batch_size=int(training["batch_size"]),
    shuffle=False,
    collate_fn=collate_patient_windows,
)
model = build_composed_model(choice, basic, choice_path=choice_path)
print("Train 환자:", len(train_dataset))
print("학습 parameter 수:", sum(p.numel() for p in model.parameters() if p.requires_grad))
batch = next(iter(train_loader))
print("첫 배치 PID:", batch[0], "waveform shape:", tuple(batch[1].shape))
del batch, model, train_loader, train_dataset

            patients  positive  negative
train            349        96       253
validation        71         8        63
test              89        10        79

Train 환자: 349
학습 parameter 수: 120674
첫 배치 PID: ['P0001'] waveform shape: (1, 128, 3, 6000)

## 3. Train·validation·best checkpoint와 MLflow

기본은 전체 학습입니다. `mlflow_logging=True`이면 로컬 `.poc.local.toml` 및 MLflow 환경 변수의 개인 계정을 확인한 뒤 학습하고, 완료한 checkpoint·architecture·집계 validation 지표를 자동 기록합니다. 연결 확인이 실패하면 학습 전에 중단합니다. 학습 도중 전송이 실패하면 로컬 모델을 보존하고 `PENDING`으로 기록합니다.

짧은 smoke는 위 실행 설정에서 `max_epochs=1`, `limit_train_patients=16`, `device_override="cpu"`, `run_final_test=False`로 바꿉니다. Train만 가중치를 학습하고 validation AP로 checkpoint를 선택합니다.

In [ ]:
run_dir = train_raw_ecg(
    choice_path,
    max_epochs=max_epochs,
    limit_train_patients=limit_train_patients,
    device_override=device_override,
    mlflow_logging=mlflow_logging,
)
print(run_dir)
display(pd.read_csv(run_dir / "training_history.csv"))
if mlflow_logging:
    print(json.loads((run_dir / "mlflow_status.json").read_text()))

## 4. Checkpoint 복원·validation 결과 확인

In [ ]:
restored_model, metadata, resolved, device = load_dl_run(run_dir, torch.device("cpu"))
print("복원 모델:", metadata["model"], "best epoch:", metadata["best_epoch"])
print(json.loads((run_dir / "metrics.json").read_text())["validation"])
display(pd.read_csv(run_dir / "validation_predictions.csv").head())
del restored_model

## 5. 최종 test 평가

위 실행 설정의 `run_final_test=True`이면 학습 후 고정된 best checkpoint·threshold로 test 평가하고, `mlflow_logging=True`이면 같은 개인 계정으로 평가 결과를 기록합니다. 설정을 비교·조정하는 중에는 `run_final_test=False`를 사용합니다. Test 평가가 기반 모델을 재학습하지는 않습니다. 원본 `eval.yaml`은 수정하지 않습니다.

In [ ]:
if run_final_test:
    from tempfile import TemporaryDirectory

    import yaml
    from Members.sang.model.evaluation.evaluation import evaluate_saved_model

    eval_path = repo / "Members/sang/model/evaluation/eval.yaml"
    eval_config = load_yaml(eval_path)
    eval_config["basic_config"] = str(basic_path)
    eval_config["evaluation"].update(
        target="dl",
        model_path=str(run_dir / "best_model.pt"),
        artifact_dir=None,
        split="test",
        mlflow_logging=mlflow_logging,
        threshold_override=None,
        results_directory=str(
            resolve_config_path(eval_config["evaluation"]["results_directory"], eval_path)
        ),
    )
    with TemporaryDirectory(prefix="raw-dl-evaluation-") as temporary:
        temporary_config = Path(temporary) / "eval.yaml"
        temporary_config.write_text(yaml.safe_dump(eval_config), encoding="utf-8")
        evaluation_dir = evaluate_saved_model(temporary_config)
    print(evaluation_dir)
    display(pd.read_csv(evaluation_dir / "predictions.csv").head())

## 기존 SQI-window 경로

기존 10초 window source는 별도 경로입니다. 필요한 경우 저장소 루트에서 `Global/.venv/bin/python -m Members.sang.model.DL.training`으로 실행합니다. Raw 학습에 기존 `sqi_pass` sidecar를 재사용하지 않습니다.

## 전송 실패 시 재시도

학습은 `from Members.sang.model.tracking.log_dl import log_dl_training_to_mlflow; log_dl_training_to_mlflow(run_dir)`로, 평가는 `from Members.sang.model.tracking.log_evaluation import log_evaluation_to_mlflow; log_evaluation_to_mlflow(evaluation_dir)`로 재학습·재평가 없이 전송합니다. 로컬 `mlflow_status.json`에서 `FINISHED` 또는 `PENDING`을 확인합니다. 환자별 예측·품질 인덱스·PID audit은 자동 업로드하지 않습니다.